In [ ]:
x=50
y="KLH-BOWRAMPET"
z=5.5
print(x,y,z)

50 KLH-BOWRAMPET 5.5


In [ ]:
myvar="KLH-BOWRAMPET"
x,y,z="Orange","banana","apple"
x1=y1=z1="Pineapple"
print(myvar,x,y,z,x1)

KLH-BOWRAMPET Orange banana apple Pineapple


In [ ]:
print("hi","hel","hru",sep='**')
print("Hello","how are you?",sep="--")

hi**hel**hru
Hello--how are you?


In [ ]:
var_name=input('interactive statement:')
print(var_name)

interactive statement:how are you
how are you


In [ ]:
a=int(input('enter the value of a:'))
b=int(input('enter the value of b:'))
c=int(input('enter the value of c:'))
print("sum of a,b,c is:",a+b+c)

enter the value of a:1
enter the value of b:2
enter the value of c:4
sum of a,b,c is: 7


In [ ]:
a=int(input('value of a:'))
b=int(input('value of b:'))
c=int(input('value of c:'))
if(a>=b and a>=c):
  print(a)
elif(b>=c and b>=a):
  print(b)
else:
  print(c)

value of a:10
value of b:10
value of c:5
10


In [ ]:
a=32.6
print(type(a))

<class 'float'>


In [ ]:
x=int(1.56)
y=float(1)
z=str('1.56')
print(x,y,z)

1 1.0 1.56


In [ ]:
b="KLH-BOWRAMPET"
print(b[5:7])
print(b[:7])
print(b[5:])
print(b[-1:-3])

OW
KLH-BOW
OWRAMPET



In [ ]:
s="KLH-BOWRAMPET"
print(s.find('M'))
print(s.lower())
print(s.capitalize())
print(s.swapcase())
print(s.title())
print(len(s))



9
klh-bowrampet
Klh-bowrampet
klh-bowrampet
Klh-Bowrampet
13


In [ ]:
i=5
while(i>0):
  print(i)
  i-=1
for k in range(1,7,2):
  print('a')

5
4
3
2
1
a
a
a


In [ ]:
import numpy as np
id=np.array([[1,2,3,4],[3,4,5,6]])
print(type(id))
print(id)
print(id.ndim)
print(id[0,2])
print(id[0,-1])
print(id[0:1])
print(id[:1])
print(id[1:])
print(id.shape)

<class 'numpy.ndarray'>
[[1 2 3 4]
 [3 4 5 6]]
2
3
4
[[1 2 3 4]]
[[1 2 3 4]]
[[3 4 5 6]]
(2, 4)


In [ ]:
import numpy as np
p=np.array([1,2,3,4,5,6])
for x in p:
  print(x)
n1=np.array([1,2,3,4])
n2=np.array([5,6,7,8])
n3=np.concatenate([n1,n2])
for x in n3:
  print(x)

1
2
3
4
5
6
1
2
3
4
5
6
7
8
